name: demo

on:
  push:
    branches: [ main ]

jobs:
  demojob:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v7.0.0

      - name: upload artifacts  
        uses: actions/upload-artifact@v7.0.1
        with:
          name: static web page
          path: index.html


          
  deploy:
    needs: demojob
    runs-on: ubuntu-latest
    steps:
      - name: get build artifacts
        uses: actions/download-artifact@v3.1.0
        with:
          name: static web page
      - name: output contents
        run: ls
      - name: deply
        run: echo "deploying----"
      
        

  
