name: demo

on:
  push:
    branches: [ main ]

jobs:
  demojob:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        run: echo "hello world"
        uses: actions/upload-artifact@v7.0.1
        with:
          name: viki
          path: |
            dist
            
        

  
